### ISSUE TITLE
Question: Equivalent plink command in js

### ISSUE THREAD

**Issue by aberbegall** [markelog/adit#3]
Currently I am using these two modules

- **Websockify**; [webSocket to TCP proxy javascript for Node.js](https://github.com/novnc/websockify/blob/master/other/js/websockify.js)

- **plink.exe**; [SSH client with port redirect for windows](https://the.earth.li/~sgtatham/putty/0.70/htmldoc/Chapter7.html)

In order to open a web socket connection with a remote VNC server (port 5900). To achieve that currently I use plink to create a ssh tunnel to a remote VNC server and redirect the remote port 5900 over ssh tunnel.

This is the plink command I execute:
> plink.exe -L 3333:localhost:5900 -i key.ppk user@remotehost -pw passphrase

And I would like to integrate that **plink** functionality into the **websockify** script.

Would that be possible with **adit**?
Thanks in advance :)

**Comment by markelog** [comment]
Adit, as underling dependency, uses a `ssh2` module and such module supports windows, so there shouldn't be any differences. At least I can't think of any.

So 

```js
new Adit('3333:localhost:5900 user@remotehost').forward()
```

Provided that the key added to ssh-agent. If it's not the case, you can provide the key in explicit manner as well – https://github.com/markelog/adit/tree/56942109595f5164bc9d53f97e28dddc8accaba5#thorough

**Comment by aberbegall** [comment]
Unfortunately I'm not able to make it work :(
I'm trying to forward the remote 5900 (linux server) to my local 3333 (windows client).

If I execute "netstat -anob" on the windows client:

- With plink.exe running: 
I can see a connection ESTABLISHED to remote host on port 22 (plink.exe process)
And a connection LISTENING on port 3333 (plink.exe process)

- With adit running:
I can see a connection ESTABLISHED to remote host on port 22  (node.exe process)
But no connection LISTENING on port 3333.. Why?

Any idea?

Note: Currently I'm using a plink private key converted to openssh format without passphrase.

This is the script I currently execute:

```js
try
{
    var adit = new adit(
    {
        host: '10.111.222.333',
        username: 'user',
        port: 22,
        key: 'openssh.ppk'
    });
    adit.open(3).then(connection => 
        {
            connection.out(
                {
                    host: 'localhost',
                    port: 5900
                }, 
                {
                    host: 'localhost',
                    port: 3333
                }).
                then(() => 
                {
                    console.log("Port forward enabled...")
                });
        }, 
        error => 
        {
            console.error(error);
        });
    adit.on('error', () => 
    {
        console.error("ERROR!")
    });        
} 
catch(e) 
{
    console.error(e);
    process.exit(2);
}
```

**Comment by aberbegall** [comment]
Ok I just figured out that I mess up the ports. Works fine like this:

```js
          connection.out(
                {
                    host: 'localhost',
                    port: 3333
                }, 
                {
                    host: 'localhost',
                    port: 5900
                }).
```

Now I need to see how I deal with private with passphrase as it seems not supported by adit, not sure if it is also a limitation of ssh2. 
I am assuming running pageant (windows ssh agent) is not supported, Am I wrong?
